// Code generated by goctl. DO NOT EDIT.
package types

type GetChatLogReadRecordsReq struct {
	MsgId string `json:"msgId"`
}

type GetChatLogReadRecordsResp struct {
	Reads   []string `json:"reads"`
	UnReads []string `json:"unReads"`
}
